#!/bin/bash
#by C4ry_Anaymouns build
echo "Enter the password to unlock the backlight permission"
sudo chmod 777 /sys/class/backlight/intel_backlight/brightness

echo " Instructions: sh blight number "
echo " ____             _    _ _       _     _   "
echo "| __ )  __ _  ___| | _| (_) __ _| |__ | |_ "
echo "|  _ \ / _  C 4 ry_Anaymouns _  | '_ \| __|"
echo "| |_) | (_| | (__|   <| | | (_| | | | | |_ "
echo "|____/ \__,_|\___|_|\_\_|_|\__, |_| |_|\__|"
echo "                           |___/           "
echo "We do not forget"
echo "We do not forgive"
echo "..."
echo ".."
echo "."

backlight=`cat /sys/class/backlight/intel_backlight/max_brightness`

echo " Maximum-brightness: ${backlight}, you turn the brightness to: ${1}, It'done "
echo $1 >/sys/class/backlight/intel_backlight/brightness
