#!/bin/bash
#by C4ry_Anonymous create
#Support Debian/Centos/Archlinux
#Log query method: cat /etc/rsyslog.conf
#
echo "# # # # # # # # # # # # # # # #"
echo "################################"
echo "#                              #"
echo "#    Clean ALL log-mission     #"
echo "#       C4ry_Anonymous         #"
echo "#                              #"
echo "################################"
echo "# # # # # # # # # # # # # # # #"
echo "!!!Please enter ROOT to work!!!"
echo "Start after 10 seconds" && sleep 10s
echo "--------------------------------------------"
echo "Clearing login information ..."
wtmp='/var/log/wtmp'
btmp='/var/log/btmp'
lastlog='/var/log/lastlog'
secure='/var/log/secure'
authlog='/var/log/auth.log'
faillog='/var/log/faillog'

sleep 3s

if [ -e $wtmp ] ; then
   cat $wtmp && cat /dev/null > $wtmp 2>/dev/null && echo 'The [wtmp] is clear'
 else
   echo '#The [wtmp] not exist'
fi

sleep 1s

if [ -e $btmp ] ; then
   cat $btmp && cat /dev/null > $btmp 2>/dev/null && echo 'The [btmp] is clear'
 else
   echo '#The [btmp] not exist'
fi

sleep 1s

if [ -e $lastlog ] ; then
   cat $lastlog && cat /dev/null > $lastlog 2>/dev/null && echo 'The [lastlog] is clear'
 else
   echo '#The [lastlog] not exist'
fi

sleep 1s

if [ -e $secure ] ; then
   cat $secure && cat /dev/null > $secure 2>/dev/null && echo 'The [secure] is clear'
 else
   echo '#The [secure] not exist'
fi

sleep 1s

if [ -e $authlog ] ; then
   cat $authlog && cat /dev/null > $authlog 2>/dev/null && echo 'The [authlog] is clear'
 else
   echo '#The [authlog] not exist'
fi

sleep 1s

if [ -e $faillog ] ; then
   cat $faillog && cat /dev/null > $faillog 2>/dev/null && echo 'The [faillog] is clear'
 else
   echo '#The [faillog] not exist'
fi

sleep 1s
echo "--------------------------------------------"
echo "Clearing used information ..."
dpkglog='/var/log/dpkg.log'
fontconfiglog='/var/log/fontconfig.log'
alternativeslog='/var/log/alternatives.log'
bootstraplog='/var/log/bootstrap.log'
aptlog='/var/log/apt/history.log'
termlog='/var/log/apt/term.log'
pacmanlog='/var/log/pacman.log'
yumlog='/var/log/yum.log'


sleep 3s

if [ -e $dpkglog ] ; then
   cat /dev/null > $dpkglog 2>/dev/null && echo 'The [dpkglog] is clear'
 else
   echo '#The [dpkglog] not exist'
fi

sleep 1s

if [ -e $fontconfiglog ] ; then
   cat /dev/null > $fontconfiglog 2>/dev/null && echo 'The [fontconfiglog] is clear'
 else
   echo '#The [fontconfiglog] not exist'
fi

sleep 1s

if [ -e $alternativeslog ] ; then
   cat /dev/null > $alternativeslog 2>/dev/null && echo 'The [alternativeslog] is clear'
 else
   echo '#The [alternativeslog] not exist'
fi

sleep 1s

if [ -e $bootstraplog ] ; then
   cat /dev/null > $bootstraplog 2>/dev/null && echo 'The [bootstraplog] is clear'
 else
   echo '#The [bootstraplog] not exist'
fi

sleep 1s

if [ -e $aptlog ] ; then
   cat /dev/null > $aptlog 2>/dev/null && echo 'The [aptlog] is clear'
 else
   echo '#The [aptlog] not exist'
fi

sleep 1s

if [ -e $termlog ] ; then
   cat /dev/null > $termlog 2>/dev/null && echo 'The [termlog] is clear'
 else
   echo '#The [termlog] not exist'
fi

sleep 1s

if [ -e $pacmanlog ] ; then
   cat /dev/null > $pacmanlog 2>/dev/null && echo 'The [pacmanlog] is clear'
 else
   echo '#The [pacmanlog] not exist'
fi

sleep 1s

if [ -e $yumlog ] ; then
   cat /dev/null > $yumlog 2>/dev/null && echo 'The [yumlog] is clear'
 else
   echo '#The [yumlog] not exist'
fi

sleep 1s

echo "--------------------------------------------"
echo "Please wait for the program to complete ..."
fail2banlog='/var/log/fail2ban.log'
firstbootlog='/var/log/first-boot.log'
cloudinitlog='/var/log/cloud-init.log'
cloudinitoutputlog='/var/log/cloud-init-output.log'
bootlog='/var/log/boot.log'
bootlog2='/var/log/boot'
debuglog='/var/log/debug'
daemonlog='/var/log/daemon.log'
croglog='/var/log/crog'
dmesglog='/var/log/dmesg'
lprlog='/var/log/lpr.log'
firewalldlog='/var/log/firewalld'
ufwlog='/var/log/ufw'
gufwlog='/var/log/gufw'
maillog="/var/log/mail.*"
mysqllog="/var/log/mysql.*"
messageslog='/var/log/messages'
syslog='/var/log/syslog'
syslog2='/var/log/syslog.1'
tallylog='/var/log/tally.log'
kernlog='/var/log/kern.log'
userlog='/var/log/user.log'
xorglog='/var/log/xorg.0.log'
apachelog="/var/log/apache2/*"
lighttpdlog="/var/log/lighttpd/*"
fscklog="/var/log/fsck/*"
apportlog='/var/log/apport.log'
ngxaccesslog='/var/log/nginx/access.log'
ngxaccesslog2='/var/log/nginx/access.log.1'
ngxerrorlog='/var/log/nginx/error.log'
ngxerrorlog2='/var/log/nginx/error.log.1'
rsyslog="/var/spool/rsyslog/*"

sleep 3s

if [ -e $fail2banlog ] ; then
   cat /dev/null > $fail2banlog 2>/dev/null && echo 'The [fail2banlog] is clear'
 else
   echo '#The [fail2banlog] not exist'
fi

sleep 1s

if [ -e $firstbootlog ] ; then
   cat /dev/null > $firstbootlog 2>/dev/null && echo 'The [firstbootlog] is clear'
 else
   echo '#The [firstbootlog] not exist'
fi

sleep 1s

if [ -e $cloudinitlog ] ; then
   cat /dev/null > $cloudinitlog 2>/dev/null && echo 'The [cloudinitlog] is clear'
 else
   echo '#The [cloudinitlog] not exist'
fi

sleep 1s

if [ -e $cloudinitoutputlog ] ; then
   cat /dev/null > $cloudinitoutputlog 2>/dev/null && echo 'The [cloudinitoutputlog] is clear'
 else
   echo '#The [cloudinitoutputlog] not exist'
fi

sleep 1s

if [ -e $bootlog ] ; then
   cat /dev/null > $bootlog 2>/dev/null && echo 'The [bootlog] is clear'
 else
   echo '#The [bootlog] not exist'
fi

sleep 1s

if [ -e $bootlog2 ] ; then
   grep -i fail /var/log/boot && cat /dev/null > $bootlog2 2>/dev/null && echo 'The [bootlog2] is clear'
 else
   echo '#The [bootlog2] not exist'
fi

sleep 1s

if [ -e $debuglog ] ; then
   cat /dev/null > $debuglog 2>/dev/null && echo 'The [debuglog] is clear'
 else
   echo '#The [debuglog] not exist'
fi

sleep 1s

if [ -e $daemonlog ] ; then
   cat /dev/null > $daemonlog 2>/dev/null && echo 'The [daemonlog] is clear'
 else
   echo '#The [daemonlog] not exist'
fi

sleep 1s

if [ -e $croglog ] ; then
   cat /dev/null > $croglog 2>/dev/null && echo 'The [croglog] is clear'
 else
   echo '#The [croglog] not exist'
fi

sleep 1s

if [ -e $dmesglog ] ; then
   cat /dev/null > $dmesglog 2>/dev/null && echo 'The [dmesglog] is clear'
 else
   echo '#The [dmesglog] not exist'
fi

sleep 1s

if [ -e $lprlog ] ; then
   cat /dev/null > $lprlog 2>/dev/null && echo 'The [lprlog] is clear'
 else
   echo '#The [lprlog] not exist'
fi

sleep 1s

if [ -e $firewalldlog ] ; then
   cat /dev/null > $firewalldlog 2>/dev/null && echo 'The [firewalldlog] is clear'
 else
   echo '#The [firewalldlog] not exist'
fi

sleep 1s

if [ -e $ufwlog ] ; then
   cat /dev/null > $ufwlog 2>/dev/null && echo 'The [ufwlog] is clear'
 else
   echo '#The [ufwlog] not exist'
fi

sleep 1s

if [ -e $gufwlog ] ; then
   cat /dev/null > $gufwlog 2>/dev/null && echo 'The [gufwlog] is clear'
 else
   echo '#The [gufwlog] not exist'
fi

sleep 1s

if [ -e $maillog ] ; then
   cat /dev/null > $maillog 2>/dev/null && echo 'The [maillog] is clear'
 else
   echo '#The [maillog] not exist'
fi

sleep 1s

if [ -e $mysqllog ] ; then
   cat /var/log/mysql.err && cat /dev/null > $mysqllog 2>/dev/null && echo 'The [mysqllog] is clear'
 else
   echo '#The [mysqllog] not exist'
fi

sleep 1s

if [ -e $messageslog ] ; then
   less $messageslog && cat /dev/null > $messageslog 2>/dev/null && echo 'The [messageslog] is clear'
 else
   echo '#The [messageslog] not exist'
fi

sleep 1s

if [ -e $syslog ] ; then
   cat /dev/null > $syslog 2>/dev/null && echo 'The [syslog] is clear'
 else
   echo '#The [syslog] not exist'
fi

sleep 1s

if [ -e $syslog2 ] ; then
   cat /dev/null > $syslog2 2>/dev/null && echo 'The [syslog2] is clear'
 else
   echo '#The [syslog2] not exist'
fi


sleep 1s

if [ -e $tallylog ] ; then
   cat /dev/null > $tallylog 2>/dev/null && echo 'The [tallylog] is clear'
 else
   echo '#The [tallylog] not exist'
fi

sleep 1s

if [ -e $kernlog ] ; then
   cat /dev/null > $kernlog 2>/dev/null && echo 'The [kernlog] is clear'
 else
   echo '#The [kernlog] not exist'
fi

sleep 1s

if [ -e $userlog ] ; then
   cat /dev/null > $userlog 2>/dev/null && echo 'The [userlog] is clear'
 else
   echo '#The [userlog] not exist'
fi

sleep 1s

if [ -e $xorglog ] ; then
   more /var/log/xorg.0.log && cat /dev/null > $xorglog 2>/dev/null && echo 'The [xorglog] is clear'
 else
   echo '#The [xorglog] not exist'
fi

sleep 1s

if [ -e $apachelog ] ; then
   cat /dev/null > $apachelog 2>/dev/null && echo 'The [apachelog] is clear'
 else
   echo '#The [apachelog] not exist'
fi

sleep 1s

if [ -e $lighttpdlog ] ; then
   cat /dev/null > $lighttpdlog 2>/dev/null && echo 'The [lighttpdlog] is clear'
 else
   echo '#The [lighttpdlog] not exist'
fi

sleep 1s

if [ -e $fscklog ] ; then
   cat /dev/null > $fscklog 2>/dev/null && echo 'The [fscklog] is clear'
 else
   echo '#The [fscklog] not exist'
fi

sleep 1s

if [ -e $apportlog ] ; then
   tail -f $apportlog && cat /dev/null > $apportlog 2>/dev/null && echo 'The [apportlog] is clear'
 else
   echo '#The [apportlog] not exist'
fi

sleep 1s

if [ -e $ngxaccesslog ] ; then
   cat /dev/null > $ngxaccesslog 2>/dev/null && echo 'The [ngxaccesslog] is clear'
 else
   echo '#The [ngxaccesslog] not exist'
fi
sleep 1s

if [ -e $ngxaccesslog2 ] ; then
   cat /dev/null > $ngxaccesslog2 2>/dev/null && echo 'The [ngxaccesslog2] is clear'
 else
   echo '#The [ngxaccesslog2] not exist'
fi

sleep 1s

if [ -e $ngxerrorlog ] ; then
   cat /dev/null > $ngxerrorlog 2>/dev/null && echo 'The [ngxerrorlog] is clear'
 else
   echo '#The [ngxerrorlog] not exist'
fi

sleep 1s

if [ -e $ngxerrorlog2 ] ; then
   cat /dev/null > $ngxerrorlog2 2>/dev/null && echo 'The [ngxerrorlog2] is clear'
 else
   echo '#The [ngxerrorlog2] not exist'
fi

sleep 1s

if [ -e $rsyslog ] ; then
   rm -r /var/spool/rsyslog/* 2>/dev/null && echo 'The [rsyslog] is clear'
 else
   echo '#The [rsyslog] not exist'
fi

sleep 1s


echo "--------------------------------------------"
echo "Please wait for clear SHELL to complete ..."

sleep 3s

if [ -e /root/.bash_history ] ; then
   cat /dev/null > /root/.bash_history 2>/dev/null && echo 'The [bash-history] is clear'
fi

sleep 1s

if [ -e /root/.zsh_history ] ; then
   cat /dev/null > /root/.zsh_history 2>/dev/null && echo 'The [zsh-history] is clear'
fi

sleep 1s
echo "--------------------------------------------"
echo "It's done !! HOPE YOUR ENJOY !!"

# a=`[ -e /etc/pacman.d/mirrorlist ] && echo 'The file exist'`
