#!/bin/bash
#by C4ry_Anonymous create
#Support Debian/Centos/Archlinux
#Log query method: cat /etc/rsyslog.conf
#
echo "# # # # # # # # # # # # # # # #"
echo "################################"
echo "#                              #"
echo "#    Clean ALL log-mission     #"
echo "#       C4ry_Anonymous         #"
echo "#                              #"
echo "################################"
echo "# # # # # # # # # # # # # # # #"
echo "!!!Please enter ROOT to work!!!"
echo "Start after 10 seconds" && sleep 10s
echo "--------------------------------------------"
echo "Clearing login information ..."
wtmp='/var/log/wtmp'
btmp='/var/log/btmp'
btmp2='/var/log/btmp.1'
lastlog='/var/log/lastlog'
secure='/var/log/secure'
authlog='/var/log/auth.log'
authlog2='/var/log/auth.log.1'
faillog='/var/log/faillog'

sleep 3s

if [ -e $wtmp ] ; then
   cat $wtmp && cat /dev/null > $wtmp 2>/dev/null && echo 'The [wtmp] is clear'
 else
   echo '#The [wtmp] not exist'
fi

sleep 1s

if [ -e $btmp ] ; then
   cat $btmp && cat /dev/null > $btmp 2>/dev/null && echo 'The [btmp] is clear'
 else
   echo '#The [btmp] not exist'
fi

sleep 1s

if [ -e $btmp2 ] ; then
   cat $btmp2 && cat /dev/null > $btmp2 2>/dev/null && echo 'The [btmp2] is clear'
 else
   echo '#The [btmp2] not exist'
fi

sleep 1s

if [ -e $lastlog ] ; then
   cat $lastlog && cat /dev/null > $lastlog 2>/dev/null && echo 'The [lastlog] is clear'
 else
   echo '#The [lastlog] not exist'
fi

sleep 1s

if [ -e $secure ] ; then
   cat $secure && cat /dev/null > $secure 2>/dev/null && echo 'The [secure] is clear'
 else
   echo '#The [secure] not exist'
fi

sleep 1s

if [ -e $authlog ] ; then
   cat $authlog && cat /dev/null > $authlog 2>/dev/null && echo 'The [authlog] is clear'
 else
   echo '#The [authlog] not exist'
fi

sleep 1s

if [ -e $authlog2 ] ; then
   cat $authlog2 && cat /dev/null > $authlog2 2>/dev/null && echo 'The [authlog2] is clear'
 else
   echo '#The [authlog2] not exist'
fi

sleep 1s

if [ -e $faillog ] ; then
   cat $faillog && cat /dev/null > $faillog 2>/dev/null && echo 'The [faillog] is clear'
 else
   echo '#The [faillog] not exist'
fi

sleep 1s
echo "--------------------------------------------"
echo "Clearing used information ..."
dpkglog='/var/log/dpkg.log'
dpkglog2='/var/log/dpkg.log.1'
fontconfiglog='/var/log/fontconfig.log'
alternativeslog='/var/log/alternatives.log'
alternativeslog2='/var/log/alternatives.log.1'
bootstraplog='/var/log/bootstrap.log'
aptlog='/var/log/apt/history.log'
termlog='/var/log/apt/term.log'
pacmanlog='/var/log/pacman.log'
yumlog='/var/log/yum.log'


sleep 3s

if [ -e $dpkglog ] ; then
   cat /dev/null > $dpkglog 2>/dev/null && echo 'The [dpkglog] is clear'
 else
   echo '#The [dpkglog] not exist'
fi

sleep 1s

if [ -e $dpkglog2 ] ; then
   cat /dev/null > $dpkglog2 2>/dev/null && echo 'The [dpkglog2] is clear'
 else
   echo '#The [dpkglog2] not exist'
fi

sleep 1s

if [ -e $fontconfiglog ] ; then
   cat /dev/null > $fontconfiglog 2>/dev/null && echo 'The [fontconfiglog] is clear'
 else
   echo '#The [fontconfiglog] not exist'
fi

sleep 1s

if [ -e $alternativeslog ] ; then
   cat /dev/null > $alternativeslog 2>/dev/null && echo 'The [alternativeslog] is clear'
 else
   echo '#The [alternativeslog] not exist'
fi

sleep 1s

if [ -e $alternativeslog2 ] ; then
   cat /dev/null > $alternativeslog2 2>/dev/null && echo 'The [alternativeslog2] is clear'
 else
   echo '#The [alternativeslog2] not exist'
fi

sleep 1s

if [ -e $bootstraplog ] ; then
   cat /dev/null > $bootstraplog 2>/dev/null && echo 'The [bootstraplog] is clear'
 else
   echo '#The [bootstraplog] not exist'
fi

sleep 1s

if [ -e $aptlog ] ; then
   cat /dev/null > $aptlog 2>/dev/null && echo 'The [aptlog] is clear'
 else
   echo '#The [aptlog] not exist'
fi

sleep 1s

if [ -e $termlog ] ; then
   cat /dev/null > $termlog 2>/dev/null && echo 'The [termlog] is clear'
 else
   echo '#The [termlog] not exist'
fi

sleep 1s

if [ -e $pacmanlog ] ; then
   cat /dev/null > $pacmanlog 2>/dev/null && echo 'The [pacmanlog] is clear'
 else
   echo '#The [pacmanlog] not exist'
fi

sleep 1s

if [ -e $yumlog ] ; then
   cat /dev/null > $yumlog 2>/dev/null && echo 'The [yumlog] is clear'
 else
   echo '#The [yumlog] not exist'
fi

sleep 1s

echo "--------------------------------------------"
echo "Please wait for the program to complete ..."
fail2banlog='/var/log/fail2ban.log'
fail2banlog2='/var/log/fail2ban.log.1'
firstbootlog='/var/log/first-boot.log'
cloudinitlog='/var/log/cloud-init.log'
cloudinitoutputlog='/var/log/cloud-init-output.log'
bootlog='/var/log/boot.log'
bootlog2='/var/log/boot'
debuglog='/var/log/debug'
debuglog2='/var/log/debug.1'
daemonlog='/var/log/daemon.log'
daemonlog2='/var/log/daemon.log.1'
croglog='/var/log/crog'
dmesglog='/var/log/dmesg'
lprlog='/var/log/lpr.log'
firewalldlog='/var/log/firewalld'
ufwlog='/var/log/ufw'
ufwlog2='/var/log/ufw.1'
gufwlog='/var/log/gufw'
maillog="/var/log/mail.*"
mysqllog="/var/log/mysql.*"
messageslog='/var/log/messages'
messageslog2='/var/log/messages.1'
syslog='/var/log/syslog'
syslog2='/var/log/syslog.1'
tallylog='/var/log/tally.log'
kernlog='/var/log/kern.log'
kernlog2='/var/log/kern.log.1'
userlog='/var/log/user.log'
userlog2='/var/log/user.log.1'
xorglog='/var/log/xorg.0.log'
apachelog="/var/log/apache2/*"
lighttpdlog="/var/log/lighttpd/*"
fscklog="/var/log/fsck/*"
apportlog='/var/log/apport.log'
ngxaccesslog='/var/log/nginx/access.log'
ngxaccesslog2='/var/log/nginx/access.log.1'
ngxerrorlog='/var/log/nginx/error.log'
ngxerrorlog2='/var/log/nginx/error.log.1'
rsyslog="/var/spool/rsyslog/*"

sleep 3s

if [ -e $fail2banlog ] ; then
   cat /dev/null > $fail2banlog 2>/dev/null && echo 'The [fail2banlog] is clear'
 else
   echo '#The [fail2banlog] not exist'
fi

sleep 1s

if [ -e $fail2banlog2 ] ; then
   cat /dev/null > $fail2banlog2 2>/dev/null && echo 'The [fail2banlog2] is clear'
 else
   echo '#The [fail2banlog2] not exist'
fi

sleep 1s

if [ -e $firstbootlog ] ; then
   cat /dev/null > $firstbootlog 2>/dev/null && echo 'The [firstbootlog] is clear'
 else
   echo '#The [firstbootlog] not exist'
fi

sleep 1s

if [ -e $cloudinitlog ] ; then
   cat /dev/null > $cloudinitlog 2>/dev/null && echo 'The [cloudinitlog] is clear'
 else
   echo '#The [cloudinitlog] not exist'
fi

sleep 1s

if [ -e $cloudinitoutputlog ] ; then
   cat /dev/null > $cloudinitoutputlog 2>/dev/null && echo 'The [cloudinitoutputlog] is clear'
 else
   echo '#The [cloudinitoutputlog] not exist'
fi

sleep 1s

if [ -e $bootlog ] ; then
   cat /dev/null > $bootlog 2>/dev/null && echo 'The [bootlog] is clear'
 else
   echo '#The [bootlog] not exist'
fi

sleep 1s

if [ -e $bootlog2 ] ; then
   grep -i fail /var/log/boot && cat /dev/null > $bootlog2 2>/dev/null && echo 'The [bootlog2] is clear'
 else
   echo '#The [bootlog2] not exist'
fi

sleep 1s

if [ -e $debuglog ] ; then
   cat /dev/null > $debuglog 2>/dev/null && echo 'The [debuglog] is clear'
 else
   echo '#The [debuglog] not exist'
fi

sleep 1s

if [ -e $debuglog2 ] ; then
   cat /dev/null > $debuglog2 2>/dev/null && echo 'The [debuglog2] is clear'
 else
   echo '#The [debuglog2] not exist'
fi

sleep 1s

if [ -e $daemonlog ] ; then
   cat /dev/null > $daemonlog 2>/dev/null && echo 'The [daemonlog] is clear'
 else
   echo '#The [daemonlog] not exist'
fi

sleep 1s

if [ -e $daemonlog2 ] ; then
   cat /dev/null > $daemonlog2 2>/dev/null && echo 'The [daemonlog2] is clear'
 else
   echo '#The [daemonlog2] not exist'
fi

sleep 1s

if [ -e $croglog ] ; then
   cat /dev/null > $croglog 2>/dev/null && echo 'The [croglog] is clear'
 else
   echo '#The [croglog] not exist'
fi

sleep 1s

if [ -e $dmesglog ] ; then
   cat /dev/null > $dmesglog 2>/dev/null && echo 'The [dmesglog] is clear'
 else
   echo '#The [dmesglog] not exist'
fi

sleep 1s

if [ -e $lprlog ] ; then
   cat /dev/null > $lprlog 2>/dev/null && echo 'The [lprlog] is clear'
 else
   echo '#The [lprlog] not exist'
fi

sleep 1s

if [ -e $firewalldlog ] ; then
   cat /dev/null > $firewalldlog 2>/dev/null && echo 'The [firewalldlog] is clear'
 else
   echo '#The [firewalldlog] not exist'
fi

sleep 1s

if [ -e $ufwlog ] ; then
   cat /dev/null > $ufwlog 2>/dev/null && echo 'The [ufwlog] is clear'
 else
   echo '#The [ufwlog] not exist'
fi

sleep 1s

if [ -e $ufwlog2 ] ; then
   cat /dev/null > $ufwlog2 2>/dev/null && echo 'The [ufwlog2] is clear'
 else
   echo '#The [ufwlog2] not exist'
fi

sleep 1s

if [ -e $gufwlog ] ; then
   cat /dev/null > $gufwlog 2>/dev/null && echo 'The [gufwlog] is clear'
 else
   echo '#The [gufwlog] not exist'
fi

sleep 1s

if [ -e $maillog ] ; then
   cat /dev/null > $maillog 2>/dev/null && echo 'The [maillog] is clear'
 else
   echo '#The [maillog] not exist'
fi

sleep 1s

if [ -e $mysqllog ] ; then
   cat /var/log/mysql.err && cat /dev/null > $mysqllog 2>/dev/null && echo 'The [mysqllog] is clear'
 else
   echo '#The [mysqllog] not exist'
fi

sleep 1s

if [ -e $messageslog ] ; then
   cat $messageslog && cat /dev/null > $messageslog 2>/dev/null && echo 'The [messageslog] is clear'
 else
   echo '#The [messageslog] not exist'
fi

sleep 1s

if [ -e $messageslog2 ] ; then
   cat $messageslog2 && cat /dev/null > $messageslog2 2>/dev/null && echo 'The [messageslog2] is clear'
 else
   echo '#The [messageslog2] not exist'
fi

sleep 1s

if [ -e $syslog ] ; then
   cat /dev/null > $syslog 2>/dev/null && echo 'The [syslog] is clear'
 else
   echo '#The [syslog] not exist'
fi

sleep 1s

if [ -e $syslog2 ] ; then
   cat /dev/null > $syslog2 2>/dev/null && echo 'The [syslog2] is clear'
 else
   echo '#The [syslog2] not exist'
fi


sleep 1s

if [ -e $tallylog ] ; then
   cat /dev/null > $tallylog 2>/dev/null && echo 'The [tallylog] is clear'
 else
   echo '#The [tallylog] not exist'
fi

sleep 1s

if [ -e $kernlog ] ; then
   cat /dev/null > $kernlog 2>/dev/null && echo 'The [kernlog] is clear'
 else
   echo '#The [kernlog] not exist'
fi

sleep 1s

if [ -e $kernlog2 ] ; then
   cat /dev/null > $kernlog2 2>/dev/null && echo 'The [kernlog2] is clear'
 else
   echo '#The [kernlog2] not exist'
fi

sleep 1s

if [ -e $userlog ] ; then
   cat /dev/null > $userlog 2>/dev/null && echo 'The [userlog] is clear'
 else
   echo '#The [userlog] not exist'
fi

sleep 1s

if [ -e $userlog2 ] ; then
   cat /dev/null > $userlog2 2>/dev/null && echo 'The [userlog2] is clear'
 else
   echo '#The [userlog2] not exist'
fi

sleep 1s

if [ -e $xorglog ] ; then
   more /var/log/xorg.0.log && cat /dev/null > $xorglog 2>/dev/null && echo 'The [xorglog] is clear'
 else
   echo '#The [xorglog] not exist'
fi

sleep 1s

if [ -e $apachelog ] ; then
   cat /dev/null > $apachelog 2>/dev/null && echo 'The [apachelog] is clear'
 else
   echo '#The [apachelog] not exist'
fi

sleep 1s

if [ -e $lighttpdlog ] ; then
   cat /dev/null > $lighttpdlog 2>/dev/null && echo 'The [lighttpdlog] is clear'
 else
   echo '#The [lighttpdlog] not exist'
fi

sleep 1s

if [ -e $fscklog ] ; then
   cat /dev/null > $fscklog 2>/dev/null && echo 'The [fscklog] is clear'
 else
   echo '#The [fscklog] not exist'
fi

sleep 1s

if [ -e $apportlog ] ; then
   tail -f $apportlog && cat /dev/null > $apportlog 2>/dev/null && echo 'The [apportlog] is clear'
 else
   echo '#The [apportlog] not exist'
fi

sleep 1s

if [ -e $ngxaccesslog ] ; then
   cat /dev/null > $ngxaccesslog 2>/dev/null && echo 'The [ngxaccesslog] is clear'
 else
   echo '#The [ngxaccesslog] not exist'
fi
sleep 1s

if [ -e $ngxaccesslog2 ] ; then
   cat /dev/null > $ngxaccesslog2 2>/dev/null && echo 'The [ngxaccesslog2] is clear'
 else
   echo '#The [ngxaccesslog2] not exist'
fi

sleep 1s

if [ -e $ngxerrorlog ] ; then
   cat /dev/null > $ngxerrorlog 2>/dev/null && echo 'The [ngxerrorlog] is clear'
 else
   echo '#The [ngxerrorlog] not exist'
fi

sleep 1s

if [ -e $ngxerrorlog2 ] ; then
   cat /dev/null > $ngxerrorlog2 2>/dev/null && echo 'The [ngxerrorlog2] is clear'
 else
   echo '#The [ngxerrorlog2] not exist'
fi

sleep 1s

if [ -e $rsyslog ] ; then
   rm -r /var/spool/rsyslog/* 2>/dev/null && echo 'The [rsyslog] is clear'
 else
   echo '#The [rsyslog] not exist'
fi

sleep 1s

echo "--------------------------------------------"
echo "Delete some file ..."

sleep 3s

ngxaccesslog3='/var/log/nginx/access.log.2.gz'
ngxaccesslog4='/var/log/nginx/access.log.3.gz'
ngxaccesslog5='/var/log/nginx/access.log.4.gz'
ngxaccesslog6='/var/log/nginx/access.log.5.gz'
ngxaccesslog7='/var/log/nginx/access.log.6.gz'
ngxaccesslog8='/var/log/nginx/access.log.7.gz'
ngxaccesslog9='/var/log/nginx/access.log.8.gz'
ngxaccesslog10='/var/log/nginx/access.log.9.gz'
ngxaccesslog11='/var/log/nginx/access.log.10.gz'
ngxaccesslog12='/var/log/nginx/access.log.11.gz'
ngxaccesslog13='/var/log/nginx/access.log.12.gz'
ngxaccesslog14='/var/log/nginx/access.log.13.gz'
ngxaccesslog15='/var/log/nginx/access.log.14.gz'
ngxaccesslog16='/var/log/nginx/access.log.15.gz'
ngxaccesslog17='/var/log/nginx/access.log.16.gz'
ngxaccesslog18='/var/log/nginx/access.log.17.gz'
ngxaccesslog19='/var/log/nginx/access.log.18.gz'
ngxaccesslog20='/var/log/nginx/access.log.19.gz'
ngxaccesslog21='/var/log/nginx/access.log.20.gz'
ngxerrorlog3='/var/log/nginx/error.log.2.gz'
ngxerrorlog4='/var/log/nginx/error.log.3.gz'
ngxerrorlog5='/var/log/nginx/error.log.4.gz'
ngxerrorlog6='/var/log/nginx/error.log.5.gz'
ngxerrorlog7='/var/log/nginx/error.log.6.gz'
ngxerrorlog8='/var/log/nginx/error.log.7.gz'
ngxerrorlog9='/var/log/nginx/error.log.8.gz'
ngxerrorlog10='/var/log/nginx/error.log.9.gz'
ngxerrorlog11='/var/log/nginx/error.log.10.gz'
ngxerrorlog12='/var/log/nginx/error.log.11.gz'
ngxerrorlog13='/var/log/nginx/error.log.12.gz'
ngxerrorlog14='/var/log/nginx/error.log.13.gz'
ngxerrorlog15='/var/log/nginx/error.log.14.gz'
ngxerrorlog16='/var/log/nginx/error.log.15.gz'
ngxerrorlog17='/var/log/nginx/error.log.16.gz'
ngxerrorlog18='/var/log/nginx/error.log.17.gz'
ngxerrorlog19='/var/log/nginx/error.log.18.gz'
ngxerrorlog20='/var/log/nginx/error.log.19.gz'
ngxerrorlog21='/var/log/nginx/error.log.20.gz'
authlog3='/var/log/auth.log.2.gz'
authlog4='/var/log/auth.log.3.gz'
authlog5='/var/log/auth.log.4.gz'
authlog6='/var/log/auth.log.5.gz'
authlog7='/var/log/auth.log.6.gz'
daemonlog3='/var/log/daemon.log.2.gz'
daemonlog4='/var/log/daemon.log.3.gz'
daemonlog5='/var/log/daemon.log.4.gz'
daemonlog6='/var/log/daemon.log.5.gz'
daemonlog7='/var/log/daemon.log.6.gz'
debuglog3='/var/log/debug.2.gz'
debuglog4='/var/log/debug.3.gz'
debuglog5='/var/log/debug.4.gz'
userlog3='/var/log/user.log.2.gz'
userlog4='/var/log/user.log.3.gz'
userlog5='/var/log/user.log.4.gz'
ufwlog3='/var/log/ufw.log.2.gz'
ufwlog4='/var/log/ufw.log.3.gz'
ufwlog5='/var/log/ufw.log.4.gz'
messageslog3='/var/log/messages.2.gz'
messageslog4='/var/log/messages.3.gz'
messageslog5='/var/log/messages.4.gz'
kernlog3='/var/log/kern.log.2.gz'
kernlog4='/var/log/kern.log.3.gz'
kernlog5='/var/log/kern.log.4.gz'
fail2banlog3='/var/log/fail2ban.log.2.gz'
fail2banlog4='/var/log/fail2ban.log.3.gz'
fail2banlog5='/var/log/fail2ban.log.4.gz'
syslog3='/var/log/syslog.2.gz'
syslog4='/var/log/syslog.3.gz'
syslog5='/var/log/syslog.4.gz'
syslog6='/var/log/syslog.5.gz'
syslog7='/var/log/syslog.6.gz'
syslog8='/var/log/syslog.7.gz'
syslog9='/var/log/syslog.8.gz'
syslog10='/var/log/syslog.9.gz'
syslog11='/var/log/syslog.10.gz'
syslog12='/var/log/syslog.11.gz'
#--------------------------------------------#
if [ -e $ngxaccesslog3 ] ; then
   rm -r $ngxaccesslog3 2>/dev/null
 else
   echo '#The [access.log.2.gz] not exist'
fi

if [ -e $ngxaccesslog4 ] ; then
   rm -r $ngxaccesslog4 2>/dev/null
 else
   echo '#The [access.log.3.gz] not exist'
fi

if [ -e $ngxaccesslog5 ] ; then
   rm -r $ngxaccesslog5 2>/dev/null
 else
   echo '#The [access.log.4.gz] not exist'
fi

if [ -e $ngxaccesslog6 ] ; then
   rm -r $ngxaccesslog6 2>/dev/null
 else
   echo '#The [access.log.5.gz] not exist'
fi

if [ -e $ngxaccesslog7 ] ; then
   rm -r $ngxaccesslog7 2>/dev/null
 else
   echo '#The [access.log.6.gz] not exist'
fi

if [ -e $ngxaccesslog8 ] ; then
   rm -r $ngxaccesslog8 2>/dev/null
 else
   echo '#The [access.log.7.gz] not exist'
fi

if [ -e $ngxaccesslog9 ] ; then
   rm -r $ngxaccesslog9 2>/dev/null
 else
   echo '#The [access.log.8.gz] not exist'
fi

if [ -e $ngxaccesslog10 ] ; then
   rm -r $ngxaccesslog10 2>/dev/null
 else
   echo '#The [access.log.9.gz] not exist'
fi

if [ -e $ngxaccesslog11 ] ; then
   rm -r $ngxaccesslog11 2>/dev/null
 else
   echo '#The [access.log.10.gz] not exist'
fi

if [ -e $ngxaccesslog12 ] ; then
   rm -r $ngxaccesslog12 2>/dev/null
 else
   echo '#The [access.log.11.gz] not exist'
fi

if [ -e $ngxaccesslog13 ] ; then
   rm -r $ngxaccesslog13 2>/dev/null
 else
   echo '#The [access.log.12.gz] not exist'
fi

if [ -e $ngxaccesslog14 ] ; then
   rm -r $ngxaccesslog14 2>/dev/null
 else
   echo '#The [access.log.13.gz] not exist'
fi

if [ -e $ngxaccesslog15 ] ; then
   rm -r $ngxaccesslog15 2>/dev/null
 else
   echo '#The [access.log.14.gz] not exist'
fi

if [ -e $ngxaccesslog16 ] ; then
   rm -r $ngxaccesslog16 2>/dev/null
 else
   echo '#The [access.log.15.gz] not exist'
fi

if [ -e $ngxaccesslog17 ] ; then
   rm -r $ngxaccesslog17 2>/dev/null
 else
   echo '#The [access.log.16.gz] not exist'
fi

if [ -e $ngxaccesslog18 ] ; then
   rm -r $ngxaccesslog18 2>/dev/null
 else
   echo '#The [access.log.17.gz] not exist'
fi

if [ -e $ngxaccesslog19 ] ; then
   rm -r $ngxaccesslog19 2>/dev/null
 else
   echo '#The [access.log.18.gz] not exist'
fi

if [ -e $ngxaccesslog20 ] ; then
   rm -r $ngxaccesslog20 2>/dev/null
 else
   echo '#The [access.log.19.gz] not exist'
fi

if [ -e $ngxaccesslog21 ] ; then
   rm -r $ngxaccesslog21 2>/dev/null
 else
   echo '#The [access.log.20.gz] not exist'
fi
#--------------------------------------------#
if [ -e $ngxerrorlog3 ] ; then
   rm -r $ngxerrorlog3 2>/dev/null
 else
   echo '#The [error.log.2.gz] not exist'
fi

if [ -e $ngxerrorlog4 ] ; then
   rm -r $ngxerrorlog4 2>/dev/null
 else
   echo '#The [error.log.3.gz] not exist'
fi

if [ -e $ngxerrorlog5 ] ; then
   rm -r $ngxerrorlog5 2>/dev/null
 else
   echo '#The [error.log.4.gz] not exist'
fi

if [ -e $ngxerrorlog6 ] ; then
   rm -r $ngxerrorlog6 2>/dev/null
 else
   echo '#The [error.log.5.gz] not exist'
fi

if [ -e $ngxerrorlog7 ] ; then
   rm -r $ngxerrorlog7 2>/dev/null
 else
   echo '#The [error.log.6.gz] not exist'
fi

if [ -e $ngxerrorlog8 ] ; then
   rm -r $ngxerrorlog8 2>/dev/null
 else
   echo '#The [error.log.7.gz] not exist'
fi

if [ -e $ngxerrorlog9 ] ; then
   rm -r $ngxerrorlog9 2>/dev/null
 else
   echo '#The [error.log.8.gz] not exist'
fi

if [ -e $ngxerrorlog10 ] ; then
   rm -r $ngxerrorlog10 2>/dev/null
 else
   echo '#The [error.log.9.gz] not exist'
fi

if [ -e $ngxerrorlog11 ] ; then
   rm -r $ngxerrorlog11 2>/dev/null
 else
   echo '#The [error.log.10.gz] not exist'
fi

if [ -e $ngxerrorlog12 ] ; then
   rm -r $ngxerrorlog12 2>/dev/null
 else
   echo '#The [error.log.11.gz] not exist'
fi

if [ -e $ngxerrorlog13 ] ; then
   rm -r $ngxerrorlog13 2>/dev/null
 else
   echo '#The [error.log.12.gz] not exist'
fi

if [ -e $ngxerrorlog14 ] ; then
   rm -r $ngxerrorlog14 2>/dev/null
 else
   echo '#The [error.log.13.gz] not exist'
fi

if [ -e $ngxerrorlog15 ] ; then
   rm -r $ngxerrorlog15 2>/dev/null
 else
   echo '#The [error.log.14.gz] not exist'
fi

if [ -e $ngxerrorlog16 ] ; then
   rm -r $ngxerrorlog16 2>/dev/null
 else
   echo '#The [error.log.15.gz] not exist'
fi

if [ -e $ngxerrorlog17 ] ; then
   rm -r $ngxerrorlog17 2>/dev/null
 else
   echo '#The [error.log.16.gz] not exist'
fi

if [ -e $ngxerrorlog18 ] ; then
   rm -r $ngxerrorlog18 2>/dev/null
 else
   echo '#The [error.log.17.gz] not exist'
fi

if [ -e $ngxerrorlog19 ] ; then
   rm -r $ngxerrorlog19 2>/dev/null
 else
   echo '#The [error.log.18.gz] not exist'
fi

if [ -e $ngxerrorlog20 ] ; then
   rm -r $ngxerrorlog20 2>/dev/null
 else
   echo '#The [error.log.19.gz] not exist'
fi

if [ -e $ngxerrorlog21 ] ; then
   rm -r $ngxerrorlog21 2>/dev/null
 else
   echo '#The [error.log.20.gz] not exist'
fi
#--------------------------------------------#
if [ -e $authlog3 ] ; then
   rm -r $authlog3 2>/dev/null
 else
   echo '#The [auth.log.2.gz] not exist'
fi

if [ -e $authlog4 ] ; then
   rm -r $authlog4 2>/dev/null
 else
   echo '#The [auth.log.3.gz] not exist'
fi

if [ -e $authlog5 ] ; then
   rm -r $authlog5 2>/dev/null
 else
   echo '#The [auth.log.4.gz] not exist'
fi

if [ -e $authlog6 ] ; then
   rm -r $authlog6 2>/dev/null
 else
   echo '#The [auth.log.5.gz] not exist'
fi

if [ -e $authlog7 ] ; then
   rm -r $authlog7 2>/dev/null
 else
   echo '#The [auth.log.6.gz] not exist'
fi
#--------------------------------------------#
if [ -e $daemonlog3 ] ; then
   rm -r $daemonlog3 2>/dev/null
 else
   echo '#The [daemon.log.2.gz] not exist'
fi

if [ -e $daemonlog4 ] ; then
   rm -r $daemonlog4 2>/dev/null
 else
   echo '#The [daemon.log.3.gz] not exist'
fi

if [ -e $daemonlog5 ] ; then
   rm -r $daemonlog5 2>/dev/null
 else
   echo '#The [daemon.log.4.gz] not exist'
fi

if [ -e $daemonlog6 ] ; then
   rm -r $daemonlog6 2>/dev/null
 else
   echo '#The [daemon.log.5.gz] not exist'
fi

if [ -e $daemonlog7 ] ; then
   rm -r $daemonlog7 2>/dev/null
 else
   echo '#The [daemon.log.6.gz] not exist'
fi
#--------------------------------------------#
if [ -e $debuglog3 ] ; then
   rm -r $debuglog3 2>/dev/null
 else
   echo '#The [debug.2.gz] not exist'
fi

if [ -e $debuglog4 ] ; then
   rm -r $debuglog4 2>/dev/null
 else
   echo '#The [debug.3.gz] not exist'
fi

if [ -e $debuglog5 ] ; then
   rm -r $debuglog5 2>/dev/null
 else
   echo '#The [debug.4.gz] not exist'
fi
#--------------------------------------------#
if [ -e $userlog3 ] ; then
   rm -r $userlog3 2>/dev/null
 else
   echo '#The [user.log.2.gz] not exist'
fi

if [ -e $userlog4 ] ; then
   rm -r $userlog4 2>/dev/null
 else
   echo '#The [user.log.3.gz] not exist'
fi

if [ -e $userlog5 ] ; then
   rm -r $userlog5 2>/dev/null
 else
   echo '#The [user.log.4.gz] not exist'
fi
#--------------------------------------------#
if [ -e $ufwlog3 ] ; then
   rm -r $ufwlog3 2>/dev/null
 else
   echo '#The [ufw.log.2.gz] not exist'
fi

if [ -e $ufwlog4 ] ; then
   rm -r $ufwlog4 2>/dev/null
 else
   echo '#The [ufw.log.3.gz] not exist'
fi

if [ -e $ufwlog5 ] ; then
   rm -r $ufwlog5 2>/dev/null
 else
   echo '#The [ufw.log.4.gz] not exist'
fi
#--------------------------------------------#
if [ -e $messageslog3 ] ; then
   rm -r $messageslog3 2>/dev/null
 else
   echo '#The [messages.2.gz] not exist'
fi

if [ -e $messageslog4 ] ; then
   rm -r $messageslog4 2>/dev/null
 else
   echo '#The [messages.3.gz] not exist'
fi

if [ -e $messageslog5 ] ; then
   rm -r $messageslog5 2>/dev/null
 else
   echo '#The [messages.4.gz] not exist'
fi
#--------------------------------------------#
if [ -e $kernlog3 ] ; then
   rm -r $kernlog3 2>/dev/null
 else
   echo '#The [kern.log.2.gz] not exist'
fi

if [ -e $kernlog4 ] ; then
   rm -r $kernlog4 2>/dev/null
 else
   echo '#The [kern.log.3.gz] not exist'
fi

if [ -e $kernlog5 ] ; then
   rm -r $kernlog5 2>/dev/null
 else
   echo '#The [kern.log.4.gz] not exist'
fi
#--------------------------------------------#
if [ -e $fail2banlog3 ] ; then
   rm -r $fail2banlog3 2>/dev/null
 else
   echo '#The [fail2ban.log.2.gz] not exist'
fi

if [ -e $fail2banlog4 ] ; then
   rm -r $fail2banlog4 2>/dev/null
 else
   echo '#The [fail2ban.log.3.gz] not exist'
fi

if [ -e $fail2banlog5 ] ; then
   rm -r $fail2banlog5 2>/dev/null
 else
   echo '#The [fail2ban.log.4.gz] not exist'
fi
#--------------------------------------------#
if [ -e $syslog3 ] ; then
   rm -r $syslog3 2>/dev/null
 else
   echo '#The [syslog.2.gz] not exist'
fi

if [ -e $syslog4 ] ; then
   rm -r $syslog4 2>/dev/null
 else
   echo '#The [syslog.3.gz] not exist'
fi

if [ -e $syslog5 ] ; then
   rm -r $syslog5 2>/dev/null
 else
   echo '#The [syslog.4.gz] not exist'
fi

if [ -e $syslog6 ] ; then
   rm -r $syslog6 2>/dev/null
 else
   echo '#The [syslog.5.gz] not exist'
fi

if [ -e $syslog7 ] ; then
   rm -r $syslog7 2>/dev/null
 else
   echo '#The [syslog.6.gz] not exist'
fi

if [ -e $syslog8 ] ; then
   rm -r $syslog8 2>/dev/null
 else
   echo '#The [syslog.7.gz] not exist'
fi

if [ -e $syslog9 ] ; then
   rm -r $syslog9 2>/dev/null
 else
   echo '#The [syslog.8.gz] not exist'
fi

if [ -e $syslog10 ] ; then
   rm -r $syslog10 2>/dev/null
 else
   echo '#The [syslog.9.gz] not exist'
fi

if [ -e $syslog11 ] ; then
   rm -r $syslog11 2>/dev/null
 else
   echo '#The [syslog.10.gz] not exist'
fi

if [ -e $syslog12 ] ; then
   rm -r $syslog12 2>/dev/null
 else
   echo '#The [syslog.11.gz] not exist'
fi

echo "--------------------------------------------"
echo "Please wait for clear SHELL to complete ..."

sleep 3s

if [ -e /root/.bash_history ] ; then
   cat /dev/null > /root/.bash_history 2>/dev/null && echo 'The [bash-history] is clear'
fi

sleep 1s

if [ -e /root/.zsh_history ] ; then
   cat /dev/null > /root/.zsh_history 2>/dev/null && echo 'The [zsh-history] is clear'
fi

sleep 1s
echo "--------------------------------------------"
echo "It's done !! HOPE YOUR ENJOY !!"

# a=`[ -e /etc/pacman.d/mirrorlist ] && echo 'The file exist'`
